// Arquivo para inserir registros ficticios na nossa aplicação
import { client, db } from "."
import { cep, cliente, endereco, ordemServico, usuario } from "./schema"

async function seed() {
  // Realizado o delete inicialmente, pois o seed pode ser realizado diversas vezes
  // Atenção: Os deletes tem que ser nesta ordem, pois se não pode dar erro de chave estrangeiras
  await db.delete(ordemServico)
  await db.delete(cliente)
  await db.delete(endereco)
  await db.delete(cep)
  await db.delete(usuario)

  // 1. Cria usuário
  await db.insert(usuario).values({
    nomeUsuario: "eletronica.barg",
    tipoUsuario: "admin",
    senha: "eletronica.barg123"
  })

  // 2. CEPs
  const ceps = await db.insert(cep).values([
    { codigoCep: "88360000", estado: "SC", cidade: "Brusque" },
    { codigoCep: "88350000", estado: "SC", cidade: "Guabiruba" },
    { codigoCep: "89000000", estado: "SC", cidade: "Blumenau" },
    { codigoCep: "88015001", estado: "SC", cidade: "Florianópolis" },
    { codigoCep: "88020001", estado: "SC", cidade: "Florianópolis" },
    { codigoCep: "88030001", estado: "SC", cidade: "Florianópolis" },
    { codigoCep: "88040001", estado: "SC", cidade: "Florianópolis" },
    { codigoCep: "88050001", estado: "SC", cidade: "Florianópolis" },
    { codigoCep: "88060001", estado: "SC", cidade: "Florianópolis" },
    { codigoCep: "88070001", estado: "SC", cidade: "Florianópolis" },
    { codigoCep: "88080001", estado: "SC", cidade: "Florianópolis" },
    { codigoCep: "88090001", estado: "SC", cidade: "Florianópolis" },
    { codigoCep: "88100001", estado: "SC", cidade: "São José" },
    { codigoCep: "88110001", estado: "SC", cidade: "São José" },
    { codigoCep: "88120001", estado: "SC", cidade: "São José" },
    { codigoCep: "88130001", estado: "SC", cidade: "São José" },
    { codigoCep: "88140001", estado: "SC", cidade: "São José" },
    { codigoCep: "88150001", estado: "SC", cidade: "São José" },
    { codigoCep: "88160001", estado: "SC", cidade: "Biguaçu" },
    { codigoCep: "88170001", estado: "SC", cidade: "Biguaçu" },
    { codigoCep: "88180001", estado: "SC", cidade: "Biguaçu" },
    { codigoCep: "88190001", estado: "SC", cidade: "Biguaçu" },
    { codigoCep: "88200001", estado: "SC", cidade: "Palhoça" },
    { codigoCep: "88210001", estado: "SC", cidade: "Palhoça" },
    { codigoCep: "88220001", estado: "SC", cidade: "Palhoça" },
    { codigoCep: "88230001", estado: "SC", cidade: "Palhoça" },
    { codigoCep: "88240001", estado: "SC", cidade: "Palhoça" },
    { codigoCep: "88250001", estado: "SC", cidade: "Palhoça" },
    { codigoCep: "88300001", estado: "SC", cidade: "Itajaí" },
    { codigoCep: "88310001", estado: "SC", cidade: "Itajaí" }
  ]).returning()

  // 3. Endereços
  const enderecos = await db.insert(endereco).values([
    { cep: ceps[0].codigoCep, bairro: "Jardim Europa", logradouro: "Rua das Rosas", numeroEndereco: 101, complemento: "Casa 1" },
    { cep: ceps[1].codigoCep, bairro: "Santa Tereza", logradouro: "Rua do Sol", numeroEndereco: 202, complemento: "Casa 2" },
    { cep: ceps[2].codigoCep, bairro: "Pioneiros", logradouro: "Rua das Árvores", numeroEndereco: 303, complemento: "Ap 101" },
    { cep: ceps[3].codigoCep, bairro: "Vila Nova", logradouro: "Rua do Comércio", numeroEndereco: 404, complemento: "Bloco A" },
    { cep: ceps[4].codigoCep, bairro: "Boa Vista", logradouro: "Rua da Alegria", numeroEndereco: 505, complemento: "Fundos" },
    { cep: ceps[5].codigoCep, bairro: "Morro da Luz", logradouro: "Rua Central", numeroEndereco: 606, complemento: "Térreo" },
    { cep: ceps[6].codigoCep, bairro: "Itaguaçu", logradouro: "Rua do Farol", numeroEndereco: 707, complemento: "Loja 1" },
    { cep: ceps[7].codigoCep, bairro: "Estação", logradouro: "Rua das Laranjeiras", numeroEndereco: 808, complemento: "Ap 302" },
    { cep: ceps[8].codigoCep, bairro: "Monte Verde", logradouro: "Rua do Lago", numeroEndereco: 909, complemento: "Casa" },
    { cep: ceps[9].codigoCep, bairro: "Serrinha", logradouro: "Rua do Campo", numeroEndereco: 1001, complemento: "Bloco C" },
    { cep: ceps[10].codigoCep, bairro: "Jardim América", logradouro: "Rua das Oliveiras", numeroEndereco: 1111, complemento: "Ap 204" },
    { cep: ceps[11].codigoCep, bairro: "Colina Verde", logradouro: "Rua dos Pinheiros", numeroEndereco: 1212, complemento: "Casa 4" },
    { cep: ceps[12].codigoCep, bairro: "Cidade Alta", logradouro: "Rua do Cedro", numeroEndereco: 1313, complemento: "Térreo" },
    { cep: ceps[13].codigoCep, bairro: "Costa Azul", logradouro: "Rua das Palmeiras", numeroEndereco: 1414, complemento: "Casa 6" },
    { cep: ceps[14].codigoCep, bairro: "Sol Nascente", logradouro: "Rua das Hortênsias", numeroEndereco: 1515, complemento: "Casa 7" },
    { cep: ceps[15].codigoCep, bairro: "Bela Vista", logradouro: "Rua das Magnólias", numeroEndereco: 1616, complemento: "Casa 8" },
    { cep: ceps[16].codigoCep, bairro: "Nova Esperança", logradouro: "Rua dos Cravos", numeroEndereco: 1717, complemento: "Ap 305" },
    { cep: ceps[17].codigoCep, bairro: "Ponta Verde", logradouro: "Rua das Violetas", numeroEndereco: 1818, complemento: "Loja 2" },
    { cep: ceps[18].codigoCep, bairro: "Parque das Nações", logradouro: "Rua do Ipê", numeroEndereco: 1919, complemento: "Casa 9" },
    { cep: ceps[19].codigoCep, bairro: "Jardim das Palmeiras", logradouro: "Rua do Manacá", numeroEndereco: 2020, complemento: "Ap 102" },
    { cep: ceps[20].codigoCep, bairro: "Horizonte Azul", logradouro: "Rua das Acácias", numeroEndereco: 2121, complemento: "Casa 10" },
    { cep: ceps[21].codigoCep, bairro: "Morada do Sol", logradouro: "Rua do Jacarandá", numeroEndereco: 2222, complemento: "Ap 203" },
    { cep: ceps[22].codigoCep, bairro: "Vale do Sol", logradouro: "Rua do Carvalho", numeroEndereco: 2323, complemento: "Bloco D" },
    { cep: ceps[23].codigoCep, bairro: "Vila Rica", logradouro: "Rua das Bromélias", numeroEndereco: 2424, complemento: "Fundos" },
    { cep: ceps[24].codigoCep, bairro: "Monte Azul", logradouro: "Rua das Camélias", numeroEndereco: 2525, complemento: "Térreo" },
    { cep: ceps[25].codigoCep, bairro: "Jardim Imperial", logradouro: "Rua das Azaleias", numeroEndereco: 2626, complemento: "Casa 11" },
    { cep: ceps[26].codigoCep, bairro: "Floresta", logradouro: "Rua das Dalias", numeroEndereco: 2727, complemento: "Ap 306" },
    { cep: ceps[27].codigoCep, bairro: "Jardim Botânico", logradouro: "Rua do Hibisco", numeroEndereco: 2828, complemento: "Bloco E" },
    { cep: ceps[28].codigoCep, bairro: "Alto da Serra", logradouro: "Rua das Begônias", numeroEndereco: 2929, complemento: "Casa 12" },
    { cep: ceps[29].codigoCep, bairro: "Serra Verde", logradouro: "Rua do Bosque", numeroEndereco: 3030, complemento: "Loja 3" }
  ]).returning()

  // 4. Clientes
  const clientes = await db.insert(cliente).values([
    {
      idEndereco: enderecos[0].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1985-11-15",
      nomeCompleto: "João da Silva",
      cpf: "12345678901",
      rg: "MG1234567",
      filiacao: "Maria da Silva e Eduardo da Silva",
      celular1: "47999990001"
    },
    {
      idEndereco: enderecos[1].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1985-11-15",
      nomeCompleto: "Ana Beatriz Souza",
      cpf: "23456789012",
      rg: "SP7654321",
      filiacao: "Caetana Souza e Carlos Souza",
      celular1: "47999990002",
      celular2: "47988880002",
    },
    {
      idEndereco: enderecos[2].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "2000-03-10",
      nomeCompleto: "Pedro Henrique Lima",
      cpf: "34567890123",
      rg: "RJ3456789",
      filiacao: "Helena Lima e Guilherma Lima",
      celular1: "47999990003",
      telefone1: "4733250003",
      telefone2: "4733250004",
    },
    {
      idEndereco: enderecos[3].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1992-07-21",
      nomeCompleto: "Mariana Oliveira Ramos",
      cpf: "45678901234",
      rg: "BA1239876",
      filiacao: "Patrícia Oliveira e Roberto Ramos",
      celular1: "47999990004"
    },
    {
      idEndereco: enderecos[4].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1978-12-03",
      nomeCompleto: "Carlos Eduardo Pinto",
      cpf: "56789012345",
      rg: "PR8765432",
      filiacao: "Ana Pinto e João Pinto",
      celular1: "47999990005",
      celular2: "47988880005"
    },
    {
      idEndereco: enderecos[5].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1988-04-11",
      nomeCompleto: "Fernanda Martins Costa",
      cpf: "67890123456",
      rg: "RS2345678",
      filiacao: "Juliana Costa e Fábio Martins",
      celular1: "47999990006"
    },
    {
      idEndereco: enderecos[6].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1995-09-14",
      nomeCompleto: "Bruno Ferreira Rocha",
      cpf: "78901234567",
      rg: "SC3456789",
      filiacao: "Márcia Rocha e Luiz Ferreira",
      celular1: "47999990007",
      telefone1: "4733250007"
    },
    {
      idEndereco: enderecos[7].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "2002-06-30",
      nomeCompleto: "Larissa Camargo Neves",
      cpf: "89012345678",
      rg: "SP8761234",
      filiacao: "Elaine Neves e Rodrigo Camargo",
      celular1: "47999990008"
    },
    {
      idEndereco: enderecos[8].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1983-01-22",
      nomeCompleto: "Thiago Almeida Sousa",
      cpf: "90123456789",
      rg: "MG2345671",
      filiacao: "Luciana Sousa e Paulo Almeida",
      celular1: "47999990009",
      telefone2: "4733250009"
    },
    {
      idEndereco: enderecos[9].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1999-10-05",
      nomeCompleto: "Juliana Ribeiro Pires",
      cpf: "01234567890",
      rg: "RJ1234321",
      filiacao: "Sônia Pires e Gabriel Ribeiro",
      celular1: "47999990010"
    },
    {
      idEndereco: enderecos[10].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1975-08-17",
      nomeCompleto: "Marcelo Dias Brito",
      cpf: "11223344556",
      rg: "CE7654321",
      filiacao: "Rita Brito e Antonio Dias",
      celular1: "47999990011"
    },
    {
      idEndereco: enderecos[11].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1990-02-19",
      nomeCompleto: "Aline Nogueira Torres",
      cpf: "22334455667",
      rg: "GO5432167",
      filiacao: "Marta Torres e Nelson Nogueira",
      celular1: "47999990012"
    },
    {
      idEndereco: enderecos[12].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1986-05-09",
      nomeCompleto: "Rafael Teixeira Luz",
      cpf: "33445566778",
      rg: "PE4567123",
      filiacao: "Teresa Luz e Mauro Teixeira",
      celular1: "47999990013",
      celular2: "47988880013"
    },
    {
      idEndereco: enderecos[13].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1993-03-25",
      nomeCompleto: "Camila Duarte Sampaio",
      cpf: "44556677889",
      rg: "PA3216549",
      filiacao: "Helena Duarte e José Sampaio",
      celular1: "47999990014"
    },
    {
      idEndereco: enderecos[14].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1980-11-01",
      nomeCompleto: "André Luiz Farias",
      cpf: "55667788990",
      rg: "AM6543210",
      filiacao: "Marina Farias e Cláudio Luiz",
      celular1: "47999990015",
      telefone1: "4733250015"
    },
    {
      idEndereco: enderecos[15].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "2001-12-18",
      nomeCompleto: "Isabela Mendes Rocha",
      cpf: "66778899001",
      rg: "MA0987654",
      filiacao: "Cristina Mendes e Roberto Rocha",
      celular1: "47999990016"
    },
    {
      idEndereco: enderecos[16].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1977-06-04",
      nomeCompleto: "Sérgio Antunes Lima",
      cpf: "77889900112",
      rg: "PB1092837",
      filiacao: "Valéria Lima e Francisco Antunes",
      celular1: "47999990017",
      telefone2: "4733250017"
    },
    {
      idEndereco: enderecos[17].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1996-09-27",
      nomeCompleto: "Tatiane Silva Freitas",
      cpf: "88990011223",
      rg: "SE0011223",
      filiacao: "Joana Freitas e Edson Silva",
      celular1: "47999990018"
    },
    {
      idEndereco: enderecos[18].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1982-04-15",
      nomeCompleto: "Rodrigo Vasconcelos Maia",
      cpf: "99001122334",
      rg: "DF3344556",
      filiacao: "Clarice Maia e Hélio Vasconcelos",
      celular1: "47999990019",
      celular2: "47988880019"
    },
    {
      idEndereco: enderecos[19].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1998-01-08",
      nomeCompleto: "Patrícia Cunha Ribeiro",
      cpf: "10111213141",
      rg: "AC4455667",
      filiacao: "Sueli Cunha e Marcos Ribeiro",
      celular1: "47999990020"
    },
    {
      idEndereco: enderecos[20].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1991-10-30",
      nomeCompleto: "Fábio Henrique Barros",
      cpf: "12131415161",
      rg: "TO1230987",
      filiacao: "Elaine Barros e Hugo Henrique",
      celular1: "47999990021"
    },
    {
      idEndereco: enderecos[21].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1987-08-12",
      nomeCompleto: "Rafaela Borges Teles",
      cpf: "13141516171",
      rg: "AL1122334",
      filiacao: "Maria Teles e Francisco Borges",
      celular1: "47999990022"
    },
    {
      idEndereco: enderecos[22].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1974-02-06",
      nomeCompleto: "Luciano Prado Queiroz",
      cpf: "14151617181",
      rg: "PI5544332",
      filiacao: "Teresa Queiroz e Adalberto Prado",
      celular1: "47999990023",
      telefone1: "4733250023"
    },
    {
      idEndereco: enderecos[23].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1994-07-17",
      nomeCompleto: "Daniela Azevedo Melo",
      cpf: "15161718191",
      rg: "RO7766554",
      filiacao: "Lúcia Azevedo e César Melo",
      celular1: "47999990024"
    },
    {
      idEndereco: enderecos[24].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1989-03-23",
      nomeCompleto: "João Paulo Cordeiro",
      cpf: "16171819202",
      rg: "RR8899001",
      filiacao: "Beatriz Cordeiro e Paulo Sérgio",
      celular1: "47999990025"
    },
    {
      idEndereco: enderecos[25].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1997-11-09",
      nomeCompleto: "Bruna Carvalho Batista",
      cpf: "17181920212",
      rg: "ES3344221",
      filiacao: "Elisângela Carvalho e Jorge Batista",
      celular1: "47999990026"
    },
    {
      idEndereco: enderecos[26].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1984-05-12",
      nomeCompleto: "Ricardo Monteiro Lopes",
      cpf: "18192021222",
      rg: "MS1100998",
      filiacao: "Denise Lopes e Henrique Monteiro",
      celular1: "47999990027",
      telefone2: "4733250027"
    },
    {
      idEndereco: enderecos[27].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1990-12-03",
      nomeCompleto: "Letícia Alves Andrade",
      cpf: "19202122232",
      rg: "MT2288776",
      filiacao: "Fernanda Alves e Ricardo Andrade",
      celular1: "47999990028"
    },
    {
      idEndereco: enderecos[28].id,
      tipoPessoa: "Física",
      sexo: "Masculino",
      dataNascimento: "1972-09-19",
      nomeCompleto: "Eduardo Borges Lima",
      cpf: "20212223242",
      rg: "AP6677889",
      filiacao: "Neide Lima e Antônio Borges",
      celular1: "47999990029"
    },
    {
      idEndereco: enderecos[29].id,
      tipoPessoa: "Física",
      sexo: "Feminino",
      dataNascimento: "1992-06-16",
      nomeCompleto: "Viviane Costa Nascimento",
      cpf: "21222324252",
      rg: "RN9988776",
      filiacao: "Cláudia Costa e Roberto Nascimento",
      celular1: "47999990030"
    }
  ]).returning();

  // 5. Ordens de Serviço
  await db.insert(ordemServico).values([
    {
      idCliente: clientes[0].id,
      aparelho: "Televisão",
      marca: "Samsung",
      modelo: "UN40J5200",
      serie: "SN123456789",
      defeito: "Não liga",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 1 - lado direito",
      situacao: "Aguardando orçamento",
      preOrcamento: "250.00",
      notas: "Cliente disse que problema começou após queda de energia."
    },
    {
      idCliente: clientes[1].id,
      aparelho: "Televisão",
      marca: "LG",
      modelo: "MS2044U",
      serie: "SN987654321",
      defeito: "Não liga",
      acessorios: "Cabo energia",
      localizacaoAparelho: "Prateleira 2 - lado direito",
      situacao: "Pendente aprovação",
      preOrcamento: "180.00",
      valorMaoDeObra: "100.00",
      valorPecas: "80.00",
      valorTotal: "180.00",
      motivos: "Problema no barramento do Backlight",
    },
    {
      idCliente: clientes[2].id,
      aparelho: "Televisão",
      marca: "Philips",
      modelo: "In153000",
      serie: "SN1122334455",
      defeito: "Tela",
      acessorios: "Sem acessórios",
      localizacaoAparelho: "Prateleira 2 - lado esquerdo",
      situacao: "Consertado e retirado",
      preOrcamento: "400.00",
      valorMaoDeObra: "200.00",
      valorPecas: "150.00",
      valorTotal: "350.00",
      motivos: "Tela",
      notas: "50% do pagamento foi realizado na entrega do aparelho.",
      dataSaida: new Date()
    },
    {
      idCliente: clientes[3].id,
      aparelho: "Televisão",
      marca: "Sony",
      modelo: "KDL-32W655D",
      serie: "SN00000003",
      defeito: "Backlight",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 1 - A",
      situacao: "Aguardando orçamento",
      preOrcamento: "250.00"
    },
    {
      idCliente: clientes[4].id,
      aparelho: "Televisão",
      marca: "LG",
      modelo: "32LK615BPSB",
      serie: "SN00000004",
      defeito: "Não liga",
      acessorios: "Cabo de energia",
      localizacaoAparelho: "Prateleira 1 - B",
      situacao: "Pendente aprovação",
      preOrcamento: "200.00",
      valorMaoDeObra: "120.00",
      valorPecas: "80.00",
      valorTotal: "200.00",
      motivos: "Fonte danificada"
    },
    {
      idCliente: clientes[5].id,
      aparelho: "Televisão",
      marca: "Samsung",
      modelo: "UN43J5200AG",
      serie: "SN00000005",
      defeito: "Tela",
      acessorios: "Sem acessórios",
      localizacaoAparelho: "Prateleira 1 - C",
      situacao: "Consertado",
      preOrcamento: "350.00",
      valorMaoDeObra: "150.00",
      valorPecas: "180.00",
      valorTotal: "330.00",
      motivos: "Substituição do painel"
    },
    {
      idCliente: clientes[6].id,
      aparelho: "Televisão",
      marca: "Philips",
      modelo: "43PFG5813/78",
      serie: "SN00000006",
      defeito: "Sem som",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 2 - A",
      situacao: "Pendente conserto",
      preOrcamento: "180.00",
      valorMaoDeObra: "90.00",
      valorPecas: "60.00",
      valorTotal: "150.00",
      motivos: "Placa de áudio com falha"
    },
    {
      idCliente: clientes[7].id,
      aparelho: "Televisão",
      marca: "AOC",
      modelo: "LE32D1452",
      serie: "SN00000007",
      defeito: "Backlight",
      acessorios: "Cabo e controle",
      localizacaoAparelho: "Prateleira 2 - B",
      situacao: "Consertado e retirado",
      preOrcamento: "260.00",
      valorMaoDeObra: "120.00",
      valorPecas: "100.00",
      valorTotal: "220.00",
      dataSaida: new Date()
    },
    {
      idCliente: clientes[8].id,
      aparelho: "Televisão",
      marca: "Panasonic",
      modelo: "TC-32FS500B",
      serie: "SN00000008",
      defeito: "Não liga",
      acessorios: "Sem acessórios",
      localizacaoAparelho: "Prateleira 2 - C",
      situacao: "Conserto negado",
      preOrcamento: "230.00",
      motivos: "Cliente não aprovou valor"
    },
    {
      idCliente: clientes[9].id,
      aparelho: "Televisão",
      marca: "TCL",
      modelo: "32S6500",
      serie: "SN00000009",
      defeito: "Tela",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 3 - A",
      situacao: "Sem conserto e retirado",
      preOrcamento: "400.00",
      motivos: "Sem peça disponível para reposição",
      dataSaida: new Date()
    },
    {
      idCliente: clientes[10].id,
      aparelho: "Televisão",
      marca: "CCE",
      modelo: "LED32G",
      serie: "SN00000010",
      defeito: "Sem som",
      acessorios: "Somente cabo",
      localizacaoAparelho: "Prateleira 3 - B",
      situacao: "Aguardando orçamento",
      preOrcamento: "150.00"
    },
    {
      idCliente: clientes[11].id,
      aparelho: "Televisão",
      marca: "Samsung",
      modelo: "UN50RU7100",
      serie: "SN00000011",
      defeito: "Backlight",
      acessorios: "Cabo HDMI",
      localizacaoAparelho: "Prateleira 3 - C",
      situacao: "Pendente conserto",
      preOrcamento: "280.00",
      valorMaoDeObra: "130.00",
      valorPecas: "100.00",
      valorTotal: "230.00"
    },
    {
      idCliente: clientes[12].id,
      aparelho: "Televisão",
      marca: "LG",
      modelo: "43UK6510",
      serie: "SN00000012",
      defeito: "Não liga",
      acessorios: "Controle e base",
      localizacaoAparelho: "Prateleira 4 - A",
      situacao: "Pendente aprovação",
      preOrcamento: "270.00",
      valorMaoDeObra: "150.00",
      valorPecas: "90.00",
      valorTotal: "240.00"
    },
    {
      idCliente: clientes[13].id,
      aparelho: "Televisão",
      marca: "Philco",
      modelo: "PH32B53DSG",
      serie: "SN00000013",
      defeito: "Tela",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 4 - B",
      situacao: "Consertado e retirado",
      preOrcamento: "320.00",
      valorMaoDeObra: "140.00",
      valorPecas: "150.00",
      valorTotal: "290.00",
      motivos: "Substituição do painel danificado",
      notas: "Cliente retirou em 24h após contato.",
      dataSaida: new Date()
    },
    {
      idCliente: clientes[14].id,
      aparelho: "Televisão",
      marca: "Samsung",
      modelo: "UN32EH4000",
      serie: "SN00000014",
      defeito: "Sem som",
      acessorios: "Cabo de energia",
      localizacaoAparelho: "Prateleira 5 - A",
      situacao: "Consertado",
      preOrcamento: "200.00",
      valorMaoDeObra: "100.00",
      valorPecas: "60.00",
      valorTotal: "160.00",
      motivos: "Placa de áudio substituída"
    },
    {
      idCliente: clientes[15].id,
      aparelho: "Televisão",
      marca: "Sony",
      modelo: "KDL-32R305B",
      serie: "SN00000015",
      defeito: "Backlight",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 5 - B",
      situacao: "Conserto negado",
      preOrcamento: "250.00",
      motivos: "Cliente optou por não realizar conserto"
    },
    {
      idCliente: clientes[16].id,
      aparelho: "Televisão",
      marca: "AOC",
      modelo: "LE40D1452",
      serie: "SN00000016",
      defeito: "Não liga",
      acessorios: "Cabo de energia",
      localizacaoAparelho: "Prateleira 5 - C",
      situacao: "Pendente conserto",
      preOrcamento: "280.00",
      valorMaoDeObra: "130.00",
      valorPecas: "110.00",
      valorTotal: "240.00",
      motivos: "Problema na fonte principal"
    },
    {
      idCliente: clientes[17].id,
      aparelho: "Televisão",
      marca: "LG",
      modelo: "32LM620BPSB",
      serie: "SN00000017",
      defeito: "Tela",
      acessorios: "Controle remoto e suporte",
      localizacaoAparelho: "Prateleira 6 - A",
      situacao: "Aguardando orçamento",
      preOrcamento: "330.00"
    },
    {
      idCliente: clientes[18].id,
      aparelho: "Televisão",
      marca: "TCL",
      modelo: "32S615",
      serie: "SN00000018",
      defeito: "Sem som",
      acessorios: "Nenhum",
      localizacaoAparelho: "Prateleira 6 - B",
      situacao: "Sem conserto e retirado",
      preOrcamento: "210.00",
      motivos: "Sem peças disponíveis no fornecedor",
      dataSaida: new Date()
    },
    {
      idCliente: clientes[19].id,
      aparelho: "Televisão",
      marca: "Panasonic",
      modelo: "TC-32FS500B",
      serie: "SN00000019",
      defeito: "Backlight",
      acessorios: "Cabo HDMI",
      localizacaoAparelho: "Prateleira 6 - C",
      situacao: "Consertado",
      preOrcamento: "260.00",
      valorMaoDeObra: "110.00",
      valorPecas: "100.00",
      valorTotal: "210.00",
      motivos: "Barra de LEDs trocada"
    },
    {
      idCliente: clientes[20].id,
      aparelho: "Televisão",
      marca: "Philips",
      modelo: "32PHG4900",
      serie: "SN00000020",
      defeito: "Não liga",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 7 - A",
      situacao: "Consertado e retirado",
      preOrcamento: "240.00",
      valorMaoDeObra: "100.00",
      valorPecas: "100.00",
      valorTotal: "200.00",
      dataSaida: new Date()
    },
    {
      idCliente: clientes[21].id,
      aparelho: "Televisão",
      marca: "Samsung",
      modelo: "T5300",
      serie: "SN00000021",
      defeito: "Tela",
      acessorios: "Cabo e controle",
      localizacaoAparelho: "Prateleira 7 - B",
      situacao: "Pendente aprovação",
      preOrcamento: "370.00",
      valorMaoDeObra: "150.00",
      valorPecas: "180.00",
      valorTotal: "330.00",
      motivos: "Tela quebrada após impacto"
    },
    {
      idCliente: clientes[22].id,
      aparelho: "Televisão",
      marca: "LG",
      modelo: "32LM631C",
      serie: "SN00000022",
      defeito: "Sem som",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 7 - C",
      situacao: "Pendente conserto",
      preOrcamento: "190.00",
      valorMaoDeObra: "90.00",
      valorPecas: "70.00",
      valorTotal: "160.00",
      motivos: "Problema na saída de áudio"
    },
    {
      idCliente: clientes[23].id,
      aparelho: "Televisão",
      marca: "Sony",
      modelo: "KDL-40W655D",
      serie: "SN00000023",
      defeito: "Backlight",
      acessorios: "Cabo de força",
      localizacaoAparelho: "Prateleira 8 - A",
      situacao: "Consertado",
      preOrcamento: "300.00",
      valorMaoDeObra: "140.00",
      valorPecas: "120.00",
      valorTotal: "260.00",
      motivos: "LEDs com fuga de corrente"
    },
    {
      idCliente: clientes[24].id,
      aparelho: "Televisão",
      marca: "Philco",
      modelo: "PH39N91DSGW",
      serie: "SN00000024",
      defeito: "Não liga",
      acessorios: "Nenhum",
      localizacaoAparelho: "Prateleira 8 - B",
      situacao: "Sem conserto e retirado",
      preOrcamento: "210.00",
      motivos: "Defeito irreversível na placa principal",
      dataSaida: new Date()
    },
    {
      idCliente: clientes[25].id,
      aparelho: "Televisão",
      marca: "TCL",
      modelo: "43S6500",
      serie: "SN00000025",
      defeito: "Tela",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 8 - C",
      situacao: "Consertado e retirado",
      preOrcamento: "420.00",
      valorMaoDeObra: "180.00",
      valorPecas: "190.00",
      valorTotal: "370.00",
      motivos: "Tela danificada por pressão",
      dataSaida: new Date()
    },
    {
      idCliente: clientes[26].id,
      aparelho: "Televisão",
      marca: "LG",
      modelo: "32LK615B",
      serie: "SN00000026",
      defeito: "Sem som",
      acessorios: "Cabo HDMI",
      localizacaoAparelho: "Prateleira 9 - A",
      situacao: "Aguardando orçamento",
      preOrcamento: "210.00"
    },
    {
      idCliente: clientes[27].id,
      aparelho: "Televisão",
      marca: "Panasonic",
      modelo: "TC-L42ET5B",
      serie: "SN00000027",
      defeito: "Backlight",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 9 - B",
      situacao: "Pendente conserto",
      preOrcamento: "310.00",
      valorMaoDeObra: "140.00",
      valorPecas: "120.00",
      valorTotal: "260.00",
      motivos: "Falha total na iluminação traseira"
    },
    {
      idCliente: clientes[28].id,
      aparelho: "Televisão",
      marca: "Samsung",
      modelo: "UN40NU7100",
      serie: "SN00000028",
      defeito: "Tela",
      acessorios: "Suporte de mesa",
      localizacaoAparelho: "Prateleira 9 - C",
      situacao: "Conserto negado",
      preOrcamento: "390.00",
      motivos: "Orçamento excede valor do produto"
    },
    {
      idCliente: clientes[29].id,
      aparelho: "Televisão",
      marca: "AOC",
      modelo: "43S5195",
      serie: "SN00000029",
      defeito: "Não liga",
      acessorios: "Controle remoto",
      localizacaoAparelho: "Prateleira 10 - A",
      situacao: "Consertado",
      preOrcamento: "250.00",
      valorMaoDeObra: "100.00",
      valorPecas: "90.00",
      valorTotal: "190.00",
      motivos: "Fonte e fusível queimados"
    }
  ])
}

seed().finally(() => {
  client.end()
})